name: hummingbot
channels:
    - conda-forge
    - defaults
dependencies:
    - aiounittest=1.4.1
    - bidict
    - coverage=5.5
    - gql
    - nomkl=1.0
    - nose=1.3.7
    - nose-exclude
    - numpy=1.23.5
    - numpy-base=1.23.5
    - pandas=1.5.3
    - pip=23.1.2
    - prompt_toolkit=3.0.20
    - pydantic=1.9.2
    - pytest==7.3.2
    - python=3.10.12
    - pytables=3.8.0
    - scipy=1.10.1
    - tabulate==0.8.9
    - typing-extensions<4.6.0
    - zlib=1.2.13
    - joblib==1.3.2
    - icecream==2.1.3
    - pip:
          - 0x-contract-addresses==3.0.0
          - 0x-contract-wrappers==2.0.0
          - 0x-order-utils==4.0.0
          - aiohttp==3.*
          - aioprocessing==2.0.0
          - aioresponses
          - appdirs==1.4.3
          - async-timeout
          - asyncssh==2.13.1
          - pyOpenSSL==21.0.0
          - appnope==0.1.3
          - base58==2.1.1
          - cachetools==4.0.0
          - commlib-py==0.10.6
          - cryptography==3.4.7
          - cython==3.0.0a10
          - diff-cover==5.1.2
          - docker==5.0.3
          - dydx-v3-python==2.0.1
          - ethsnarks-loopring==0.1.5
          - flake8==3.7.9
          - importlib-metadata==0.23
          - injective-py==0.6.0.7
          - mypy-extensions==0.4.3
          - pandas_ta==0.3.14b
          - yarl==1.*
          - pre-commit==2.18.1
          - psutil==5.7.2
          - ptpython==3.0.20
          - pyjwt==1.7.1
          - pyperclip==1.7.0
          - python-telegram-bot==12.8
          - requests==2.*
          - rsa==4.7
          - ruamel-yaml==0.16.10
          - signalr-client-aio==0.0.1.6.2
          - sqlalchemy==1.4.*
          - substrate-interface==1.6.2
          - solders==0.1.4
          - web3==5.31.4
          - websockets==9.1
          - ujson==5.7.0
          - git+https://github.com/CoinAlpha/python-signalr-client.git
